version: '3.7'

services:
  streamantix:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./models:/app/models
      - ./.secrets:/app/.secrets
    ports:
      - "4343:4343"
    environment:
      TWITCH_TOKEN_PATH: /app/.secrets/twitch_tokens.json

volumes:
  models:
